Make sure flyspell is loaded when adding the prog-mode-hook
emacs-exordium/exordium pull request #171
Opened 2020-12-21 00:39 UTC by steve-downey

Make sure the flyspell package is loaded and configured if using
flyspell-prog-mode as a prog-mode-hook.

----

#

2020-12-21 13:55 UTC, pkryger commented on modules/init-prog-mode.el
I don't think this is needed anymore
```suggestion
```

2020-12-21 13:56 UTC, pkryger requested changes
I think there's a redundant hook addition. Doesn't matter that much, since `add-hook` doesn't add the same thing twice, does it? Just to avoid confusion, I'd rather remove the old way.

2020-12-22 01:08 UTC, steve-downey commented on modules/init-prog-mode.el
Yes, there's no good reason to do it twice.

2020-12-22 06:46 UTC, pkryger approved these changes
LGTM

2020-12-22 06:46 UTC, merged