Switch to custom require function and modernise code base
emacs-exordium/exordium pull request #227
Opened 2024-11-28 16:53 UTC by pkryger

A few weeks ago @steve-downey [mentioned](https://github.com/emacs-exordium/exordium/pull/226#discussion_r1824899019) that it could be beneficial to have a custom load method for Exordium's modules that loads exactly what is asked, and not what is available on the load path. I found the idea compelling and decided to give it a go.

By the sheer amount of changes you can probably guess that implementation took me more than a single afternoon. It is just shy of 80 commits. Perhaps it will be more digestable to review it commit by commit, especially the ones that change a single module. I added a few notes to commit messages that may explain things a bit.

While I was working I decided to give the code a bit of TLC with the following goals in mind:

- use the new `exordium-require` to load Exordium modules,
- enable byte compilation in CI: it's enabled twice: first time to intall all external packages, second time to actually do linting (with `flycheck`),
- eliminate all compiler warnings: the `flycheck` method is used for that, as this is something I have enabled when editing code and it gives me instantenous feedback,
- eliminate all `checkdoc` warnings,
- ensure relevant built-in packages are upgraded to newest versions (see `:exordium-force-elpa`),
- standardise and switch all key bindings to `bind-key`,
- adding a small bits and pieces here and there, for example: extra configuration for `ac-window`, use `xref` in `init-elisp`, etc.

Note that I removed all file cookies preventing byte compilation: after all one of the goals for this change was to eliminate as many compiler warnings as possible. The Exordium should be compileable now, and I even gave it a couple runs with loading from `.elc`. However, following advice from Info node `(use-package) Byte-compiling` I wouldn't encourage to do that. See a bit more in the points to follow up below.

I think it reached the state where is good to review. I hope I managed to find fixes and workarounds for most CI instabilities. I've seen it failing from time to time, but I traced these to issues outside of our control: something happens with ELPA signatures or packages are updated in ELPA in middle of installation.

@pgrenet and @steve-downey: There are a few things I was wondering while working on this change.

1. Removal or `rtags`. I remember having a blast using it back in a day. All these did you mean fixes for my fat fingered typos were marvelous. However,in the age of LSP and `eglot` and `lsp-mode` it seems a bit obsolete. Personally, I haven't used it for years!

2. Perhaps we can extract code that is actually worth compiling into separate modules (i.e., `defun`s and `defmacro`s). We could add some kind of a policy and allow/block lists to Exordium to select modules that are worth compiling. Idea modeled on `ipchains` back from 90ies 😉.

3. Dropping support for Emacs-27. While I tried to research if my changes are still applicable to Emacs-27 (i.e, does that particular function already exist there?) I don't really have an environment where I can reliably and consistently test it. CI doesn't support it any more, and setting up a separate container is a bit too involved in my opinion. Also: I have a few things that I would like to bring to Exordium, but these require at least Emacs-28i.e., `difftastic`, `modus-theme`. And developing conditional loading is getting harder without CI support. Is Emacs-27 something that is still required?

4. In a similar vain: what about Emacs-28. It is not that old and has a substantial number of features, but I guess we could agree on a future timeline to remove it, say some time after Emacs-30 has been released? Unless there's complete lack of interest supporting it, then we can remove soon.

Please let me know if you think these deserve separate issues, but regardless I would really appreciate your feedback.

2024-11-28 19:11 UTC, steve-downey commented
We're in the short run to an emacs 30 release, so I'd be comfortable dropping support for 27. 

The other thing that I'd noticed is that if you use-package from within a use-package, emacs doesn't think it's user requested, and will mark it as a candidate for auto removal, and that's slightly annoying. 

Will actually review later, this is just all meta-commentary.

2024-11-30 19:53 UTC, philippe-grenet commented
Will review also later, it’s a big one. But I think it is totally fine to remove rtags and EMacs 27.

2024-12-02 23:55 UTC, philippe-grenet commented
Good news, it starts! I haven't found an issue yet. I am slowly reviewing commit by commit as you suggested.

2024-12-03 08:51 UTC, pkryger commented
> Good news, it starts! I haven't found an issue yet. I am slowly reviewing commit by commit as you suggested.

Thanks for the update. Take your time and let me know if I broke known workflows anywhere.

FWIW, I am still learning how various parts are interacting with each other and may be updating a few bindings (how they are declared, NOT which keys are bound to which command). But will push as a separate commit to minimise interference with your review.

2024-12-03 18:46 UTC, philippe-grenet requested changes
a few typos in log messages

2024-12-03 18:46 UTC, philippe-grenet commented on init.el
> +  (message "Loadding tapped before-init file: %s" tapped-file)
Typo: Loading

2024-12-03 18:46 UTC, philippe-grenet commented on init.el
> +  (message "Loadding tapped prefs file: %s" tapped-file)
Typo: Loading

2024-12-03 18:46 UTC, philippe-grenet commented on init.el
> +  (message "Loadding tapped after-init file: %s" tapped-file)
Typo: Loading

2024-12-05 00:32 UTC, philippe-grenet commented
I'm having some trouble with basic things, like it doesn't open an org mode file because 'magit-git-str: Symbol’s function definition is void: magit-process-git'. This symbol is defined, so it looks like a compilation error. I don't think this is related ti my taps but maybe I am wrong. Unfortunately I need more time to troubleshoot. Tomorrow I am going to clone your own repo and start from your branch, and debug from there.

2024-12-05 09:54 UTC, pkryger commented
> I'm having some trouble with basic things, like it doesn't open an org mode file because 'magit-git-str: Symbol’s function definition is void: magit-process-git'. This symbol is defined, so it looks like a compilation error. I don't think this is related ti my taps but maybe I am wrong. Unfortunately I need more time to troubleshoot. Tomorrow I am going to clone your own repo and start from your branch, and debug from there.

Sorry about that. I have just tried fresh (i.e., `rm -rf ~/.emacs.d/elpa*` then start Emacs), and I have no issues with `org-mode`. Let me know how it goes.

Just a thought, but have you considered adding your taps to CI. Similar to what I have done. Perhaps @steve-downey you could add yours too. Not withstanding getting to know which features we use (i.e., `lsp-mode` is not my cup of tea, I prefer `eglot`), I think it would be beneficial to know when we introduce changes breaking someone else's workflow.

2024-12-05 12:22 UTC, philippe-grenet commented
> Sorry about that. I have just tried fresh (i.e., `rm -rf ~/.emacs.d/elpa*` then start Emacs), and I have no issues with `org-mode`. Let me know how it goes.

Did that, same issue. I'll figure it out, I just need to find a couple of hours free.

2024-12-05 12:55 UTC, philippe-grenet commented
Ok so same error as mine.

2024-12-05 13:26 UTC, pkryger commented
Managed to reproduce it. I think this has something to do with deferred loading. I created and pushed a workaround in Exordium, but will check if I can reproduce on vanilla Emacs to properly understand the issue. Apologies for wasting your time.

2024-12-05 19:56 UTC, philippe-grenet commented
That fixed it, thanks. No apologies necessary. On with the testing and code review...

2024-12-05 20:13 UTC, philippe-grenet commented
I get minor issues with org-mode. And this warning keeps happening as I work with org files:
```
⛔ Warning (emacs): Org version mismatch.
This warning usually appears when a built-in Org version is loaded
prior to the more recent Org version.

Version mismatch is commonly encountered in the following situations:

1. Emacs is loaded using literate Org config and more recent Org
   version is loaded inside the file loaded by ‘org-babel-load-file’.
   ‘org-babel-load-file’ triggers the built-in Org version clashing
   the newer Org version attempt to be loaded later.

   It is recommended to move the Org loading code before the
   ‘org-babel-load-file’ call.

2. New Org version is loaded manually by setting ‘load-path’, but some
   other package depending on Org is loaded before the ‘load-path’ is
   configured.
   This "other package" is triggering built-in Org version, again
   causing the version mismatch.

   It is recommended to set ‘load-path’ as early in the config as
   possible.

3. New Org version is loaded using straight.el package manager and
   other package depending on Org is loaded before straight triggers
   loading of the newer Org version.

   It is recommended to put

    (straight-use-package 'org)

   early in the config.  Ideally, right after the straight.el
   bootstrap.  Moving ‘use-package’ :straight declaration may not be
   sufficient if the corresponding ‘use-package’ statement is
   deferring the loading.

4. A new Org version is synchronized with Emacs git repository and
   stale .elc files are still left from the previous build.

   It is recommended to remove .elc files from lisp/org directory and
   re-compile.
```

2024-12-05 21:55 UTC, pkryger commented
> I get minor issues with org-mode. And this warning keeps happening as I work with org files:
> [...]

I have seen warnings like this a few times. However, never in real usage, only in CI. I've moved `init-org` to be loaded early in the process, but something seems to be pulling it in. Are these warnings coming up after emacs has been restarted (as opposed in the first start session)? I will investigate further.

2024-12-06 00:07 UTC, philippe-grenet commented
I just did this: delete my pr/227 branch, delete alpa repo, fetch pr/227 branch with your latest commit, start Emacs, open a .org file. Same errors (many times).

This PR is sizable, which makes it hard to figure out what could be the cause. I'm wondering if we should go instead with smaller PRs, the first one introducing your new require and then trying to apply it module after module? Just a thought, feel free to disagree.

2024-12-06 10:33 UTC, pkryger commented
Thank you for your patience @philippe-grenet. I would like to try last push with the current state of art. I updated how the early init is done. Basically, installing critical components in synchronous manner, and ensuring modules are not loaded too early. This is a bit slower since everything stops waiting for critical packages to recompile (`org-mode` is over a 100 files!). Only then turning async on. If you still see issues, could you try using [this branch](https://github.com/pkryger/exordium/tree/dbg-print-load-path-and-history) with extra debug prints and capture what you can see in the affected emacs session?

If this doesn't work, then I think I'll revert to smaller incremental changes.

2024-12-06 12:11 UTC, philippe-grenet commented
One think I notice now is that it doesn't install my `exordium-extra-packages`. Glancing at commit [876799a](https://github.com/emacs-exordium/exordium/pull/227/commits/876799a33b33970e11aa6e09f8c5a254d370505c), it looks like this list is not added into `exordium-extra-pinned` anymore.

2024-12-06 12:17 UTC, pkryger commented
> One think I notice now is that it doesn't install my `exordium-extra-packages`. Glancing at commit [876799a](https://github.com/emacs-exordium/exordium/pull/227/commits/876799a33b33970e11aa6e09f8c5a254d370505c), it looks like this list is not added into `exordium-extra-pinned` anymore.

Should be fixed in latest [force-push](https://github.com/emacs-exordium/exordium/compare/06f7184514e7bc63787ced1eda72834e796549d4..cecac1d398a2c8f37abf033b2b0579c9338340be)

2024-12-06 13:38 UTC, philippe-grenet commented
Yeah that fixes it, thanks. I'm going to use this PR as my daily driver for a new days and will report any issue. And I will dedicate 1 hour per day on the code review itself. Thanks @pkryger .

2024-12-06 14:36 UTC, pkryger commented
Let me know your findings. I guess it is not only me who is not using all Exordium features. And in some cases not even aware of. I think that why I brought up the idea of adding people's taps to CI, to see what may have been broken.

2024-12-07 17:22 UTC, philippe-grenet reviewed
Still learning the new exordium-require.

2024-12-07 17:22 UTC, philippe-grenet commented on modules/init-require.el
> +;; different Exordium modules.  One example is the `:diminish'/`:delight' which
Nitpicking: "This is dictated by **the** difficulty **of** syncing different calls <s>of</s> **to** `use-package' when these are spread across different Exordium modules.

2024-12-07 17:22 UTC, philippe-grenet commented on modules/init-require.el
> +(defmacro exordium-require (feature &optional location &rest declarations)
Personally I would have made `location` an `&key` argument instead of `&optional`. I see only one usage of location in `init.el`, for Rtags, and location is nil because you want to also use the declarations. That would require using `cl-defmacro` I think.
```lisp
(exordium-require 'init-rtags nil
                  :functions (rtags-auto-complete))
```

2024-12-07 17:22 UTC, philippe-grenet commented on modules/init-require.el
> +(defvar exordium--require-nesting-list nil
Do we have to use a global variable for this? Can't we use a parameter (recursion-count) instead?

2024-12-08 10:43 UTC, pkryger commented on init.el
> +  (message "Loadding tapped before-init file: %s" tapped-file)
fixed in 1e02586fbb5ec6456e1a4eba4fdadf5b447a1631

2024-12-08 10:43 UTC, pkryger commented on init.el
> +  (message "Loadding tapped prefs file: %s" tapped-file)
fixed in 1e02586fbb5ec6456e1a4eba4fdadf5b447a1631

2024-12-08 10:43 UTC, pkryger commented on init.el
> +  (message "Loadding tapped after-init file: %s" tapped-file)
fixed in 1e02586fbb5ec6456e1a4eba4fdadf5b447a1631

2024-12-08 10:43 UTC, pkryger commented on modules/init-require.el
> +(defvar exordium--require-nesting-list nil
I think this is the simplest solution. I copied what `require` [does](https://github.com/emacs-mirror/emacs/blob/3fe787ad4d5894df5b540dbd195128118c949c7c/src/fns.c#L3707).

A parameter would need to be transferred explicitly (can't relay on user to do that).

Alternative, I can think of - but not necessarily know if this is feasible, nor possible -  is advising all file loading functions (`load`, `require`, `exordium-require`, what else?) and pass the parameter as some kind of context.

2024-12-08 10:43 UTC, pkryger commented on modules/init-require.el
> +(defmacro exordium-require (feature &optional location &rest declarations)
Not necessairly `cl-defmacro`. Could be a `(&rest plist)`. Let me see if how involved would that be...

2024-12-08 10:43 UTC, pkryger commented on modules/init-require.el
> +;; different Exordium modules.  One example is the `:diminish'/`:delight' which
Thanks for that. I struggled with this sentence a lot. For my deffence: we don't have prepositions in Polish ¯\_(ツ)_/¯

2024-12-08 11:30 UTC, pkryger commented on modules/init-require.el
> +(defmacro exordium-require (feature &optional location &rest declarations)
b3f56f9ec87b55fbbefe8e5be4868ddd9018a293, with regards from unit tests and `helm-ag-edit`

2024-12-08 11:34 UTC, pkryger commented
> Still learning the new exordium-require.

Let me know if you have any questions. Let's see if I learned anything during the process 🤔

2024-12-08 15:10 UTC, philippe-grenet commented
> Let me know if you have any questions. Let's see if I learned anything during the process 🤔

This is advanced Lisp! I'm learning new things like `condition-case-unless-debug` or Emacs internals like `byte-compile-current-file`.

2024-12-08 16:10 UTC, philippe-grenet reviewed
Making progress on the modules.

2024-12-08 16:10 UTC, philippe-grenet commented on modules/init-helm.el
> +  (helm-split-window-other-side-when-one-window 'right)
So I noticed that you prefer your popup windows to be on the right side 🙂 My preference is at the bottom. Should we make this a pref? (we can do this later)

2024-12-08 16:10 UTC, philippe-grenet commented on modules/init-highlight.el
> +    ;; let's keep that implementation, by ensuring load order.
Great!

2024-12-08 16:37 UTC, pkryger reviewed
> This is advanced Lisp! I'm learning new things like condition-case-unless-debug or Emacs internals like byte-compile-current-file.

I have been learning these recently too, but probably in a less systematic way - more what I needed at the moment. So happy to hear if you can see any improvements 😎.

2024-12-08 16:37 UTC, pkryger commented on modules/init-highlight.el
> +    ;; let's keep that implementation, by ensuring load order.
😌

2024-12-08 16:37 UTC, pkryger commented on modules/init-helm.el
> +  (helm-split-window-other-side-when-one-window 'right)
Sure thing. Pref it is! Actually, a value added over just carbon copy into a single package setting. Let's postpone until next PR.

2024-12-08 16:37 UTC, pkryger commented on modules/init-autocomplete.el
> +    (load (file-name-concat (locate-user-emacs-file "modules") "init-require"))))
De facto it is here only to silence compiler warnings. The `init-require` has been loaded in init.el already. But complier run more on a file by file basis and is run as a part of lint process (two times, each slightly different) and as a Flycheck in interactive mode. So it may be fiddly...  But will think about it.

2024-12-08 16:37 UTC, pkryger commented on modules/init-bde-style.el
> +                                        ; checkdoc-params: (element)
Silences `checkdoc` linter. I tried to be pragmatic about this, and when I had an idea how to incorporate `ARGUMENT` into docstring I did. But when I struggled in that moment, I opted for silencer. Happy to update if you have a suggestion.

Also see the leading underscore comment.

2024-12-08 16:37 UTC, pkryger commented on modules/init-bde-style.el
> +(defun bde-comment-offset (_element)
Even better, you can now only use `(ignore element)` to the same effect. But it seems these young chaps learnt the old Elisp a new trick 😎. It not only silences unused variable warning when compiling, but also missing `_ELEMENT` in docsctring. See note for `; checkdoc-params: (arg1 arg2)` for my approach to these.

2024-12-08 16:51 UTC, philippe-grenet commented on modules/init-autocomplete.el
> +    (load (file-name-concat (locate-user-emacs-file "modules") "init-require"))))
Ok then that's fine then.

2024-12-08 17:16 UTC, philippe-grenet reviewed
I have `exordium-complete-mode` set to `:company`, but it seems like company-mode isn't enabled. Here is my test:
- Open any file (foo.txt). `describe-mode` doesn't include Company.
- If I do the same thing outside of PR 227 it does show Company.

2024-12-08 17:16 UTC, philippe-grenet commented on modules/init-autocomplete.el
> +  :if (eq exordium-complete-mode :auto-complete)
This shouldn't be required because you do a `pcase exordium-complete-mode` in init.el. But if you want to keep it, let's also add it into init-company.el.

2024-12-08 20:20 UTC, pkryger commented on modules/init-autocomplete.el
> +  :if (eq exordium-complete-mode :auto-complete)
You're correct. I think I'd rather delete it here.

2024-12-08 22:38 UTC, pkryger commented
> I have `exordium-complete-mode` set to `:company`, but it seems like company-mode isn't enabled. Here is my test:
> 
> * Open any file (foo.txt). `describe-mode` doesn't include Company.
> * If I do the same thing outside of PR 227 it does show Company.

I have not changed it, and `init-company.el` unconditionally calls `global-company-mode`, which is not deferred. As usual in cases like that - works for me. But that may be my desktop or something in my tap. I will take a deeper dive into it tomorrow. Can you check what are values of `company-global-mode` and `company-global-modes` variables?

2024-12-09 00:05 UTC, philippe-grenet commented
> Can you check what are values of `company-global-mode` and `company-global-modes` variables?

It looks like Company isn't loaded at all: `(featurep 'company)` returns nil. Also:
* Variable `global-company-mode` (defined in company-autoload.el) is nil
* `company-global-modes` is undefined
* The `:config:` section doesn't seem to have executed. The variable `company-backends` is void, `rtags-completions-enabled` is nil.

I didn't figure out why yet.

2024-12-09 06:08 UTC, steve-downey commented on modules/init-bde-style.el
> +(defun bde-comment-offset (_element)
See, for example, https://www.gnu.org/software/emacs/manual/html_node/elisp/Converting-to-Lexical-Binding.html
where it's mentioned using _name to silence unused variable warnings.

2024-12-09 08:36 UTC, pkryger commented
> I didn't figure out why yet.

I haven't figure out what exactly is happening in your case. But with the help of wrapping the `use-package` call in `init-company.el` in `macroexpand` (and `C-c M-e` a.k.a. `M-x pp-eval-last-sexp` ) I could see that instead of  `(require 'company)` there was `(require-after-load 'company ...)`. Although, further macro expansion of code generated by `:bind` shows that <kbd>C-.</kbd> should be bound in `global-keymap`. The binding should be to `compan-complete` which is an autoloaded function 🤔.

I have pushed a fix ensuring that `company` is fully configured during startup (see b566158f228d99fdd29ae5992d61fa629c96ed5e). But before you apply it, would you mind satisfying my curiosity and check if <kbd>C-.</kbd> is bound to `company-complete` in your `global-keymap`? And what does the `(symbol-function 'company-complete)` eval to.

2024-12-09 11:48 UTC, philippe-grenet commented
> But before you apply it, would you mind satisfying my curiosity and check if C-. is bound to `company-complete` in your `global-keymap`? And what does the `(symbol-function 'company-complete)` eval to.

* <kbd>C-.</kbd> is bound to company-complete -- "company-complete is an autoloaded, interactive and natively compiled
function defined in company.el."
* `(symbol-function 'company-complete)` --> `#<subr company-complete>`

2024-12-09 12:08 UTC, philippe-grenet commented
Ok Company works for me now with your latest commit. Thanks Przemek.

2024-12-09 12:11 UTC, philippe-grenet commented on modules/init-bde-style.el
> +(defun bde-comment-offset (_element)
Ah well, TIL.

2024-12-09 14:20 UTC, pkryger commented
> * C-. is bound to company-complete -- "company-complete is an autoloaded, interactive and natively compiled
>   function defined in company.el."
> * `(symbol-function 'company-complete)` --> `#<subr company-complete>`

Hmm... and in such a situation company didn't work? Were these obtained when `(featurep 'company)` was nil? This would surprise me. Anyway... given that

> Ok Company works for me now with your latest commit. Thanks Przemek.

lets move to next thing. :)

2024-12-13 23:46 UTC, steve-downey commented
It seems that tap directories aren't added to the load-path anymore? Or at least I'm getting an error on one of mine which `requires` a file that's provided in the same directory. It seems reasonable to pull in additional functions by requier rather than putting everything in before or after-init? 
https://github.com/steve-downey/org.tap

2024-12-14 15:37 UTC, pkryger commented
> It seems that tap directories aren't added to the load-path anymore? Or at
> least I'm getting an error on one of mine which `requires` a file that's
> provided in the same directory. It seems reasonable to pull in additional
> functions by requier rather than putting everything in before or after-init?

I fully agree with you (although my personal `after-init` is over 2k lines long
and still growing ¯\_(ツ)_/¯). However, I removed addition of anything to
`load-path` on purpose. I think it may be a bit confusing as it is indirect and
the taps that are cloned may influence each other. I left
[a note how to add to `load-path` in a tap]
(https://github.com/pkryger/exordium/blob/exordium-require/README.md?plain=1#L1032-L1043).
Please let me know if this is something you can work with.

2024-12-14 17:29 UTC, philippe-grenet reviewed
Making slow progress on the code review. I hope the holidays will give me the time I need to really do it right. progress is slow:
<img width="419" alt="Screenshot 2024-12-14 at 12 28 33" src="https://github.com/user-attachments/assets/7f87c063-cf9d-4cd9-a11a-89b2a11d68f3" />

2024-12-14 17:29 UTC, philippe-grenet commented on modules/init-flb-mode.el
> +;;; init-flb-mode.el --- Minor mode for making buffers local to each frame -*- lexical-binding: t -*-
By the way, this module was written for a single user (Julien Bibollet, remember him?). I don't even know if he uses it anymore. That would be a candidate for deletion, alongside Rtags.

2024-12-14 17:29 UTC, philippe-grenet commented on modules/init-flb-mode.el
> +  "Remove any dead frames from variable `flb--frame-buffers'."
I like using the imperative mood for all docstrings (like in BDE style). There are other functions above you can set to the same model.

2024-12-17 12:05 UTC, pkryger reviewed
> Making slow progress on the code review. I hope the holidays will give me the time I need to really do it right. [...]

No worries. I keep working on future things, but can postpone merging them to Exordium until we have this one behind us.

2024-12-17 12:05 UTC, pkryger commented on modules/init-flb-mode.el
> +;;; init-flb-mode.el --- Minor mode for making buffers local to each frame -*- lexical-binding: t -*-
Of course I remember Julien 😎. Would you mind checking with him if that's the case? Even if he wants that I'll be opting for removing `flb-mode` into something more maintained, like for example [`perspective-el`](https://github.com/nex3/perspective-el).

2024-12-17 12:05 UTC, pkryger commented on modules/init-require.el
> +(defvar exordium--require-nesting-list nil
Another one would be to use symbol function property (see `function-put`/`function-get`). But not sure if this wouldn't muddy waters even more. 

@philippe-grenet Let me know if you're feeling strongly about removing the variable, and I will try to come up with a solution.

2024-12-17 12:16 UTC, philippe-grenet commented
> > Making slow progress on the code review. I hope the holidays will give me the time I need to really do it right. [...]
> 
> No worries. I keep working on future things, but can postpone merging them to Exordium until we have this one behind us.

From my viewpoint, this can be merged. It is stable and I can finish looking at the changes later. Mostly what I want to do is spend more time on the new "require" feature. @steve-downey are you okay with merging?

2024-12-19 23:52 UTC, philippe-grenet commented
Ok. @pkryger time to merge?

2024-12-20 08:43 UTC, pkryger commented
> Ok. @pkryger time to merge?

Yeah - I was to do it yesterday, but there is some new issue with CI not liking `sqlite3` . Was hoping for a quick fix and merge. But that proved to be more difficult. Will take a look at it today and try do come up with something, then merge

2024-12-20 10:27 UTC, merged